#' Title
#'
#' @param consencus.result the list generated by \code{\link[ConsensusClusterPlus]{ConsensusClusterPlus}}.
#' @param k cluster number.
#'
#' @return Area under the curve.
cal.auc <- function(consencus.result, k){
  consencus.matrix <- consencus.result[[k]]$consensusMatrix
  cdf <- ecdf(c(consencus.matrix))

  # Get diagonal after removing first column and last row
  t <- sort(diag(consencus.matrix[-nrow(consencus.matrix), -1]))

  # Make a "lagged" t for performing vectorized calculation
  lagged.t <- c(NA, head(t, -1))
  # cdf object is closure that is not subsettable, should be called once used
  cdf.t <- cdf(t)
  sum((t[-1] - lagged.t[-1]) * cdf.t[-1])
}
